name: second


on:
  workflow_call:
    inputs:
      image:
        description: "image name"
        required: false
        type: string
        default: my-app

      tag:
        description: "image-tag"
        default: latest
        type: string

    secrets:
      docker_username:
        required: true


      docker_token:
        required: true

    outputs:
      my-outputs:
        value: ${{ jobs.reuse-sec.outputs.my-outputs }}



jobs:
  reuse-sec:
    runs-on: ubuntu-latest

    outputs:
      my_job_output: ${{ steps.image.outputs.my_job_output }}

    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_token }}


      - name: docker build
        run: |

          docker build -t ${{ inputs.image }} .
          docker tag ${{ secrets.docker_username }}/${{ inputs.image }}:${{ inputs.tag }}
          docker push ${{ secrets.docker_token }}/${{ inputs.image }}:${{ inputs.tag }}


      - name: set image output
        id: image
        run: echo "image_url=docker.io/${{ inputs.image }}:${{ inputs.tag }}" >> "$GITHUB_OUTPUT"

                                                                                            
