name: deployin_in_container

on:
  workflow_dispatch:

jobs:
  cont:
    runs-on: ubuntu-latest

    steps:
      - name: pull image
        run: docker pull yjawlekar/my-app:latest


      - name: run
        run: docker run -d --name my-container -p 8000:8000 yjawlekar/my-app:latest

      - name: debug container state
        run: |
          echo "--- docker ps ---"
          docker ps -a
          echo "--- docker logs ---"
          docker logs my-container

      - name: wait for container
        run: sleep 5



      - name: health check
        id: health
        run: |
          if curl -s -f http://localhost:8000/health > /dev/null ; then
            echo "- Status: PASSED" >> $GITHUB_OUTPUT
            echo "Health check PASSED"
          else
            echo "- Status: FAILED" >> $GITHUB_OUTPUT
            echo "Health check FAILED"
          fi
      

      - name: stop and remove
        if: always ()
        run: |
          docker stop my-container || true
          docker rm my-container || true

      - name: write summary
        if: always ()
        run: |
          echo "## Health Check Report" >> $GITHUB_STEP_SUMMARY
          echo "- Image: myapp:latest" >> $GITHUB_STEP_SUMMARY
          echo "status - ${{ steps.health.outputs.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- Time: $(date)" >> $GITHUB_STEP_SUMMARY

      - name: fail job if unhealthy
        if: steps.health.output.status == 'Failed'
        run: exit 1

        
        


