name: main

on:
  push:
    branches: [ "main" ]


jobs:
  first:
    uses: ./.github/workflows/reusable-build-test.yml


  second:
    needs: first
    uses: ./.github/workflows/reusable-docker.yml
    with:
      tag: |
        ${{ inputs.image }}:latest
        ${{ inputs.image }}:sha-${{ github.sha }}


  deploy:
    runs-on: ubuntu-latest
    needs: second
    environments: production

    steps:
      - name: Image deploying to prodcution
        env:
          image: ${{ needs.second.outputs.my-outputs }}
        run: echo "Deploying image- $image to production"
