name: main

on:
  push:
    branches: [ "main" ]


jobs:
  first:
    uses: ./.github/workflows/reusable-build-test.yml


  second:
    needs: first
    uses: ./.github/workflows/docker-reusable.yml
    with:
      image: my-app
      tag: latest 
    secrets:
        docker_username: ${{ secrets.DOCKER_USERNAME }}
        docker_token: ${{ secrets.DOCKER_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: second
    environment: production

    steps:
      - name: Image deploying to prodcution
        env:
          image: ${{ needs.second.outputs.my-outputs }}
        run: echo "Deploying image- $image to production"


      - name: Run trivy vulenrabilities
         id: view
         uses: aquasecurity/trivy-action@v0.36.0
         with:
           image-ref: ${{ needs.second.outputs.my-outputs }}
            format: 'table'
            output: 'trivy.txt'
            severity: 'CRITICAL,HIGH'
            exit-code: '1'


      - name: upload this to report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy.txt

